RandyGaul/cute_headers

tinyc2.h

Since the c2Poly parameters get passed as pointers to all collision functions, but never actually get modified (obviously), they should be const.
Otherwise calling the functions with const pointers doesn't work.
For example:
```
for (const c2Poly& obstacle : mObstacles)
{
c2CircletoPolyManifold(c, &obstacle, nullptr, &manifold);
// ...
}
```

Added const to c2Poly pointers since they never actually get modified

---

tinyc2.h

Explicit ```inline``` before ```__attribute__((always_inline))```
seems to be necessary on Linux, GCC. This fix the following warning for
functions using C2_INLINE:
warning: always_inline function might not be inlinable [-Wattributes]
C2_INLINE ...

Fix inline definition for Linux GCC

---

tinyc2.h

The structure assignment on ```c2SidePlanes()``` was using aggregate
initialization for an assignment, which does not work for C (tested on
GCC 6.3.1, Linux). This commit fix that by assigning each member of the
structure to the new value.

Fix assignment of structure

---

tinyc2.h

For the purpose of cross-platform functionality, the macro was changed
to a function.

Change macro C2_PLANE_AT to a function

---

tinyc2.h

Contact point before:
Contact point after:
I add the normal direction multiplied by `B.r` to `B.p` to get the correct contact point:
```c
c2v n = l != 0 ? c2Mulvs(d, 1.0f / l) : c2V(0, 1.0f);
m->count = 1;
m->depths[ 0 ] = r - l;
m->contact_points[ 0 ] = c2Sub(B.p, c2Mulvs(n, B.r));
m->normal = n;
```

Fix contact point in c2CircletoCircleManifold

---

examples_tinysound/sdl_demo/main.cpp
tinysound.h

This adds the ability to load through [SDL_RWops](https://wiki.libsdl.org/SDL_RWops) objects.
Three new functions:
- `tsLoadWAVRW()`
- `tsLoadOGGRW()`
- `tsReadRWToMemory()`

tinysound: Add ability to load SDL_RWops

---

examples_tinysound/sdl_demo/Makefile

This makes it easier to test out the sdl_demo. Just run `make` to compile sdl_demo.

tinysound: Add a Makefile for sdl_demo

---

tinysound.h

This allows to define your own `TS_SDL_PATH` for cases where *SDL2/SDL.h* is not at *SDL2/SDL.h*. Just change the `TS_SDL_PATH` define accordingly.

tinysound: Allow changing SDL2/SDL.h path

---

tinysound.h

Fixes error:
`error: static declaration of 'tsSDL_AudioCallback' follows non-static declaration`

tsSDL_AudioCallback is now static in both places

---

tinysound.h

Remove GCC 'selectany' attribute warning

---

tinyc2.h

This fixes issue #53 and a typo inside c2Collide.

tinyc2: Fix #53, Inconsistent normal direction if using c2Collide

---

tinysound.h

It's just to remove "unused function" warning

Comment out unused `atan` functions

---

tinyfiles.h

Fixed inconsistency within TF_PLATFORM preprocessor variables -> Originally defined as TF_PLATFORM and TF_UNIX, but then accessed as TN_PLATFORM and TN_UNIX, causing library to not compile at all

Changed TN_UNIX to TF_UNIX

---

tinyc2.h

I found some inconsistencies with contact points in c2CircletoCapsuleManifold:
And fixed it:
And i found the same inconsistency and a wrong depth calculation in c2CapsuletoCapsuleManifold:
And fixed it:

tinyc2: Fix contact points and normal in capsule manifolds

---

tinypath.h

* Fixes compilation errors, tpPop & tpPopExt aren't given enough arguments
* Fixes whitespace around parantheses and some function/macro names (they started with 'tf')
* Fix tpPop for unix style paths starting at '/' with one subitem, all unit tests are passing
* Add two unit tests for previous fix and add unit tests for 'pop' & 'ext' arguments

tinypath: Fix compilation errors, file formatting and add some unit tests

---

tinypath.h

* Finally fixes tpPop when the path starts from the root directory and has one subitem
* Fixes tpPopExt if the given path has no file extension

tinypath: Fix bug in tpPop and tpPopExt

---

tinypath.h

I had a look at `tpPop` but it didn't really fit the problem so i decided to do it without. I added some tests to cover the special cases i found. I made a requirement for n to be bigger than 6, in some cases 3 would be enough but i think 6 is reasonable.
Some examples with "/path/to/file.vim":
```
n = 17: "/path/to/file.vim"
n = 16: "/pat.../file.vim"
n = 12: ".../file.vim"
n = 11: ".../file..."
```
more examples are in the tests.
I also added tests for the return value of `tpCompact`

tinypath: Implement tpCompact

---

tinyfiles.h

The #defines were referenced in #59 and fixed in #61 but somehow they snuck back in.
The missing `#include <time.h>` caused a compilation error on Linux due to the use of `difftime()`
I also noticed that time_a is overwritten [here](https://github.com/RandyGaul/tinyheaders/blob/master/tinyfiles.h#L442) instead of assing path_b's time to time_b. I haven't used this function, but I figured that's what you were going for.

Typo in #defines and Missing #include for time.h

---

tinygl.h

Fix typo in tinygl.h header comment

---

tinymath2d.h

Including the header more than once would have caused a linker error because the impact method tinymath2d.h is not inline.

The "impact" method must be inline to avoid double definition error in tinymath2d.h

---

cute_tiled.h

I'm confident about all the changes, except for the last one in `cute_tiled_load_map_from_memory` I didn't spend enough time looking at the code to prove myself it was correct, and I wasn't using that function 😄.

Moved several declarations and qualified a literal to make g++ happy

---

cute_files.h

#107
I ran examples_cute_files/main.c with no issue, the new `examples_cute_files/a/2.subext.txt` was detected as having a `.txt` extension.

fix for cf_get_ext to use the last '.' for extensions, and a test file.

---

cute_time.h

Note: I didn't test that it doesn't work before the change. And I didn't test it after the change either. Just common sense.

cute_time: mark prev value as static in POSIX implementation

---

cute_sound.h

These changes allow the header to compile on MSVC with no crashes or memory access faults, however, the audio itself doesn't play.

Moving variable declarations to get around permissive goto statement issues.

---

cute_png.h

The following line suggests that the atlas background color is intended to be black.
```C
#define CUTE_PNG_ATLAS_EMPTY_COLOR        0x000000FF
```
When running the example, it is white however. This is because memset is used, which operates on bytes instead of ints. I changed it so that any color value can be set.
Additionally, there was a check:
`CUTE_PNG_CHECK(atlas_image_size, "out of mem");`
Which should check that `atlas_pixels` was successfully allocated, but the `atlas_image_size` variable is checked instead.

Fix bugs in atlas creation

---

cute_png.h

Currently if `CUTE_PNG_ATLAS_MUST_FIT` is defined 0 and an image does not fit, a segfault occurs because of a null dereference at `best_fit->min;`.
Also, if the `nodes` list is reallocated, the `best_fit` pointer now points to freed memory. I tried forcing a reallocation every time, and the example gives a Segmentation Fault. With this fix it doesn't anymore.

Fix segfaults / dangling pointer issues of best_size

---

cute_c2.h

I added names to the API structs because I need them in my use case. The reason I need them is because the LuaJIT FFI doesn't parse the typedefs as the actual names of the structures, despite the typedef being parsed and usable in most cases. However, when I run `tostring(c2AABB())`, I get `"cdata<struct 14572>"` as my return value. Initially, I tried to work around this without editing the cute_c2 header, but I can't fully fix all use cases unless the FFI-generated type information is correct. Having the struct defined as a number is unacceptable for me because the number changes as I add new C libraries.

Added names to unnamed cute_c2 API structs

---

cute_sid.h

I just saw #157 and think that is what @newparadime meant. In your example in cute_sid.h you write `SID("string")` but later you define it as `SID(str, len)`. I fixed that and the string length that is being passed.

Fix string length passed to sid_FNV1a

---

cute_spritebatch.h

It causes compilation issues on FreeBSD and is unused

Remove SPRITEBATCH_ALLOCA

---

cute_tiled.h

The macro `cute_tiled_expect` does not wrap the argument `expect` with brackets, leading to operator precedence issues if the argument contains, for example, a ternary operator.
This fixes these issues by replacing `expect` in the macro with `(expect)`.

Fix macro expanding issue in #178

---

.gitignore
cute_tiled.h

Error	C4996	'strnicmp': The POSIX name for this item is deprecated. Instead,
use the ISO C and C++ conformant name: _strnicmp.

Fix MSVC Error C4996 in #181, Update for Tiled 1.3.3 JSON format

---

cute_tiled.h

When trying to use the functions cute_tiled_get_flags and
cute_tiled_unset_flags, gcc gave me 'undefined symbol' error. I think
these are meant to be static.

Fix undefined symbol: cute_tiled_get_flags, cute_tiled_unset_flags

---

cute_sound.h

Since members of `cs_context_t` are private, I added a getter for `playing`. This is needed in my game, where several sounds are adjusted globally at arbitrary times.
Also fixed a C++ warning with stb_vorbis.

cute_sound.h: Add cs_get_playing

---

cute_tiled.h

Improve logging info (prints the file and line where the error is from in the json file).
Fix a bug in cute_tiled_read_int when the value being parsed is a float.  Tiled editor changed the type of some of its values from int to float which made the map loading fail. Easiest solution was to make cute_tiled_read_int able to deal with floats.

Improve logging info and fix int parsing when it's a float

---

cute_tiled.h

Skip editorsettings field when parsing an external tileset so we don't completely fail when we attempt the load.

cute_tiled.h - Skip editorsettings field when parsing external tilesets

---

cute_sync.h

This got reverted in a previous commit, doing another PR.

Fix typo in cute_thread_wait declaration

---

cute_aseprite.h

Hello!
First of all, thanks so much for these amazing libraries, love em!
I've been playing around with cute_aseprite, and it worked great until I turned my attention to slices.
No matter what I did, I would get a segfault, if the aseprite file had any slices in it. 
After a little debugging session, I figured out that the slices were freed twice, I've removed the second `free()` call and now it works just fine!
I wanted to save everyone else using this amazing library from doubting themselves for a few hours, so I wanted to merge this fix into the official repo :) 
Thanks, Egor.

Fixed double freeing of slices

---

cute_tiled.h

Hello again :)
Continuing my path down the headers, this time spotted a little quirk/?change? with tiled-exported map files,
the `compressionLevel` is now set to `0`, if you export without any compression (`CVS`).
The library would freak out because it isn't `-1`, so I've added the expected `0` value along side `-1`.
Thanks, Egor.

Compression level 0 in tiled specification also means no compression

---

cute_aseprite.h

cute_aseprite.h was throwing two errors when compiling on windows with cl.exe, these two updates fix those issues.

Fixed two compile errors with cl.exe

---

cute_math.h
cute_math2d.h

Title says it all.
I just tested, whether the code compiles with my changes, does compute_mouse_ray actually compute the right result? I feel like it is missing
```
pf[0] /= pf[3];
pf[1] /= pf[3];
pf[2] /= pf[3];
```
right after the mul, but I haven't checked.

Fixed buffer overflow in cute_math.h and error in invert_safe.

---

cute_tiled.h

I noticed intern/deintern functions follow the style `intern_something` or `deintern_something`. `string_deintern` breaks this style. I renamed `string_deintern` to `deintern_string` to match the naming style.

Rename 'string_deintern' to 'deintern_string' to match naming style

---

cute_tiled.h

This change introduces a `CUTE_TILED_FILEIO` define to allow changing how file reads take place.

tiled: Add CUTE_TILED_STDIO to overwrite file input and snprintf

---

cute_png.h

Having the definition include the name of the file it's allowing overwriting may make a bit more sense than `FILEIO`.

png: Update CUTE_PNG_FILIO to be STDIO

---

cute_aseprite.h

Having the `CUTE_ASEPRITE_FILEIO` definition match the name of the header file it is re-implementing may make a bit more sense.

aseprite: Update CUTE_ASEPRITE_FILEIO to be STDIO

---

cute_aseprite.h

This change brings the GCC warnings from ~60 to ~8.

aseprite: Fix a bunch of GCC warnings

---

cute_tiled.h

Tiled switch to string-based version number in JSON map format in version 1.6, this fix is backwards compatible.
Also minor formatting fixes.

cute_tiled.h: fix for string-based map version

---

cute_c2.h

This is a pedantic point, but in a C function with no argument list declared is different from one which takes no arguments, declared via taking void in the argument list.
Reference: https://stackoverflow.com/questions/693788/is-it-better-to-use-c-void-arguments-void-foovoid-or-not-void-foo
This is actually causing me problems because I'm trying to use cute_c2 from Zig and it's getting confused by the empty argument list on an inline function. This PR just updates the c2 identity functions to explicitly take no arguments.

c2: Explicitly mark identity functions as taking void arguments

---

cute_tiled.h

I had a bug where my image file with a space in its name wouldn't get loaded.
It was caused by `cute_tiled_next()` being called in `cute_tiled_read_string_internal()`, since `cute_tiled_next()` skips all spaces without knowing if the space is part of a string value.
I add another function `cute_tiled_string_next()` which does the same thing except does not skip spaces for string values should be taken as is without skipping anything in them.

Fix cute_tiled skipping spaces in string values

---

cute_files.h
cute_filewatch.h
cute_sync.h
examples_cute_files/main.c

I was having issues when trying to cross-compile Windows binaries on Linux using Mingw-w64 with the `cute_files.h` header. It looks like Mingw needs the `Windows.h` header to be all lowercase in order to successfully include it.
Most of the relevant inclusions across the `cute_headers` code are already lowercase, this change just converts the rest.

Convert <Windows.h> inclusions to lowercase

---

cute_aseprite.h

I have an older ASE file (circa 2014), which in Aseprite, shows a layer at full opacity.  But as written to disk, the "layer opacity has valid value" flag is set to false (0) and the layer opacity is set to zero.  The current cute_aseprite code ignores the "Layer opacity has valid value" flag.  This patch changes the behavior to match Aseprite.
Note that if I re-save the 2014 file in a current version of Aseprite (1.2.25 or 1.3 beta), the "layer opacity has valid value" flag gets set to 1 and the opacity gets set to 255.

If layer opacity does not have a valid value, use full opacity.

---

cute_aseprite.h

ncluding cute_asesprite.h from a cpp file under vs2019 doesn't work because of the C style initialization of the return value. tweaking the return makes it c/c++ portable

make msvc cpp compatible

---

cute_spritebatch.h

This adds the ability to register premade atlases in cute_spritebatch with an image_id (spritebatch_register_premade_atlas). Then if you push a sprite with the same image_id it will use your provided minx, miny, maxx, maxy as uv coordinates. It will also call the normal texture handle creation callbacks to load the atlas to the GPU and provide a texture_id.
If you clean up the registered image_id (spritebatch_cleanup_premade_atlas). It will mark it for deletion, and it will be destroyed in the next defrag call.
Did not put any documentation yet, and maybe fetch function signature needs to change? or the user can set the uv coordinates for the fetched sprite.
Also, the cleanup might need to be enhanced a little to avoid problems registering same image_id (for reloading)

Initial support for premade atlases

---

cute_aseprite.h

This fixes up two compilation errors I was running into...
``` bash
In file included from main.c:4:
../cute_aseprite.h: In function ‘s_color’:
../cute_aseprite.h:886:13: error: expected expression before ‘{’ token
886 |    result = { 0, 0, 0, 0 };
|             ^
../cute_aseprite.h: In function ‘cute_aseprite_load_from_memory’:
../cute_aseprite.h:1165:4: error: implicit declaration of function ‘CUTE_ASSERT’ [-Werror=implicit-function-declaration]
1165 |    CUTE_ASSERT(size_read == chunk_size);
|    ^~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:2: example] Error 1
```

aseprite: Fix compilation errors

---

cute_tiled.h

Minor typo: string.h should be strings.h

Fixed minor typo: string.h should be strings.h

---

cute_tiled.h

I changed a Windows include without checking first to see it was the right one. It turns out _strnicmp is located in "string.h" not "strings.h" as I had assumed.

 Revert erroneously changing string.h in favor of strings.h in STRPOOL_EMBEDDED_STRNICMP define

---

cute_tiled.h

Some platforms do not provide that function. This way, the use of `snprintf` can be explicitly deactivated:
```C
#define CUTE_TILED_SNPRINTF(ARGS...) (void)(ARGS)
#define CUTE_TILED_IMPLEMENTATION
#include <cute_tiled.h>
```

Add preprocessor guard around CUTE_TILED_SNPRINTF

---

cute_c2.h

`cute_c2.h:399:13: error: unknown type name ‘c2TOIResult’; use ‘struct’ keyword to refer to the type
399 | CUTE_C2_API c2TOIResult c2TOI(const void *A, C2_TYPE typeA, const c2x *ax_ptr, c2v vA, const void *B, C2_TYPE typeB, const c2x *bx_ptr, c2v vB, int use_radius);
|             ^~~~~~~~~~~
|             struct `

add missing typedef for c2TOIResult in cute_c2.h

---

cute_sound.h

Fixes the lines that do nothing and give a warning.
I also added `#ifndef SDL_h_` around the SDL2 include because it's possible for the user to want to use their own SDL2 include, for example in my case I build SDL2 from source so I include by doing `#include "SDL.h"`.

fix cute_sound warnings on MacOS

---

cute_aseprite.h
cute_png.h
cute_sound.h
cute_tiled.h

This adopts the pattern introduced in [cute_sound.h](https://github.com/RandyGaul/cute_headers/blob/master/cute_sound.h#L449) to split the individual `CUTE_*_STDIO` defines into their individual defines.
It gives quite a bit more control over how the defines are leveraged.

Split up the CUTE_*_STDIO defines

---

cute_aseprite.h

This fixes up a few compiler warnings...
``` bash
cute_aseprite.h: In function ‘s_build’:
cute_aseprite.h:540:69: warning: conversion to ‘uint32_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
540 |                         tree[slot] = (code << (32 - (uint32_t)len)) | (i << 4) | len;
|                                                                     ^
cute_aseprite.h: In function ‘s_stored’:
cute_aseprite.h:559:33: warning: comparison of promoted bitwise complement of an unsigned value with unsigned [-Wsign-compare]
559 |         CUTE_ASEPRITE_CHECK(LEN == (uint16_t)(~NLEN), "Failed to find LEN and NLEN as complements within stored (uncompressed) stream.");
|                                 ^~
cute_aseprite.h:406:46: note: in definition of macro …
```

aseprite: Fix compiler warnings

---

cute_math.h

* Fix GCC ignored attribute `always_inline`; [1]
* Fix GCC attribute `selectany` ignored
- Attribute only available on Windows target[2]
- Fix with alternative [3]
[1]: https://stackoverflow.com/q/32432596/183120
[2]: https://gcc.gnu.org/onlinedocs/gcc-4.2.4/gcc/Variable-Attributes.html
[3]: https://stackoverflow.com/q/4826612/183120
Fixes #321.

Fix ignored attributes selectany, always_inline

---

cute_sound.h

This fixes a segmentation fault when using non windows platforms if a thread was spawned. Now the thread is correctly finalized.

Fix segmentation fault when cs_shutdown

---

cute_sound.h

if we have ```s_ctx->separate_thread``` equal to true and call ```cs_stop_all_playing_sounds()``` with no sounds playing, we never unlock the mutex
bugfix: added call to ```cs_unlock()``` before the early (no sounds playing) return
PS thanks for this awesome library! 🙂

bugfix cs_stop_all_playing_sounds()

---

cute_net.h

When compiling with clang on windows MSC_VER is defined and can conflict, leading to an unclear error (below). The real cause is the alignment macro which has accidentally used the MSVC compatible one instead of the clang compatible one.
```c++
cute_net.h(1663,24): error: default initialization of an object of const type 'const uint32_t [24]'
static const uint32_t coeffs[24] __declspec(align(16)) = {
^
cute_net.h(1663,34): error: expected ';' after top level declarator
static const uint32_t coeffs[24] __declspec(align(16)) = {
^
;
cute_net.h(1663,57): error: expected unqualified-id
static const uint32_t coeffs[24] __declspec(align(16)) = {
```

[cute_net] fix compiling with clang on windows

---

cute_png.h

Integer overflow appears to be the cause of #335. This patch fixes the test case and https://github.com/dbohdan/hicolor/issues/2.

cute_png: check for image size int overflow on load

---

cute_png.h

Right now cute_png does not compile out-of-the-box on NetBSD and OpenBSD because they don't have `alloca.h`. I think `alloca.h` is a Linux (GNU and musl libc) quirk. With this patch cute_png seems to work perfectly (my project's 20+ tests pass) on Net- and OpenBSD. (It likely works on FreeBSD, although I have not tested. And maybe on macOS, too?)

cute_png: only #include alloca.h on Linux

---

cute_c2.h

- Deleted the C2_TYPE_NONE enum value, because it's useless and give warnings like enumeration value 'C2_TYPE_NONE' not handled in switch.
- Removed the use of true and false because it gives an error of undeclared identifier in some compilers. (and we don't want to include stdbool.h)

Compilation errors/warning fixes

---

cute_png.h
cute_sound.h
cute_spritebatch.h

This updates the references to memcpy across the three includes to make use of their associated MEMCPY macros

Fix use of memcpy across cute_png, cute_sound, and cute_spritebatch

---

.gitignore
cute_sound.h
examples_cute_sound/sdl_demo/Makefile
examples_cute_sound/sdl_demo/main.c

This change introduces three possible defines:
```
CUTE_SOUND_PLATFORM_WINDOWS
CUTE_SOUND_PLATFORM_APPLE
CUTE_SOUND_PLATFORM_SDL
```
This allows easily selecting the platform from your compiler definitions. Rather than specifying something like...
```
-DCUTE_SOUND_PLATFORM=2
```
... and having to figure out what "2" means, you can use...
```
-DCUTE_SOUND_PLATFORM_APPLE
```
The automatic platform detection is still in place, this just makes it easier to define within your compiler definitions. This is similar to `CUTE_SOUND_FORCE_SDL`, but can be applied to all platforms.

cute_sound: Add CUTE_SOUND_PLATFORM_* Defines

---

cute_tiled.h

This is related to #362 
Newer versions of Tiled seem to use this the same way as earlier `type` so this just uses the same struct-field.

cute_tiled: overload class with type

---

cute_aseprite.h

This is a required change because in Aseprite (v1.2.40 as of writing) the slice can have both the 9-slice and pivot modes enabled, whereas the code picks one exclusively.
Closes https://github.com/RandyGaul/cute_headers/issues/371

cute_aseprite: fix slice pivot parse bug

---

cute_c2.h

Alright, I'd be lying if said I fully understand what I am doing here, but this will not stop me :sweat_smile:
I am (very) slowly porting cute_c2 to Go for a project of mine, and as part of this effort I am writing unit tests for everything in the library. That's how I found the issue I describe in the commit message:
-----
The time (`t`) component of the raycast result was incorrect when the ray ended right on the edge of the AABB. For example:
```c
c2AABB aabb = {-2.0, -1.0, 3.0, 4.0};
c2Ray ray = {{-4.0, 2.0}, {1.0, 0.0}, 2.0};
c2Raycast out;
int res = c2RaytoAABB(ray, aabb, &out);
printf("t=%f\n", out.t);
```
This would print a `t` value of `0.0` when it should be `2.0`.
-----
**Very important:** I tested this just very briefly on the C library, so you may want to at least do any …

Fix raycasts ending right on the edge of an AABB

---

README.md
cute_aseprite.h

With last version of aseprite (v1.3.2), when we save a file where no alpha is used in the palette, only the chunk 0x0004 is created (not the 0x2019).
0x0004 chunk support is then needed

cute_aseprite: Add chunck 0x0004 support

---

README.md
cute_aseprite.h

This builds from @redbug26 in https://github.com/RandyGaul/cute_headers/pull/376 to fix the type conversion warnings.

cute_aseprite: Add chunck 0x0004 support, and fix warnings

---

cute_aseprite.h

The line ase_tag_t tag; does not initialize tag.udata resulting in that uninitialized data getting copied when ase->tags[k] = tag; is hit.
The ase->tags array is initialized to 0 on line 930, so by working directly with the array instead of copying from the temp tag variable, the user data flags for the tag will remain 0.

Cute_Aseprite Fix #377 Uninitialized tag user data

---

cute_sound.h

Fixes compatibility wherein another library exposes `hashtable_init` and `hashtable_clear`

All hashtable functions are now static

---

cute_sound.h

Added getters to expose a number of audio source properties, These can be used for calculating the length of an audio source in seconds.

Implemented accessors for audio sources

---

cute_c2.h

Previously, the code for inflating polygons was behaving inconsistently with regards to the other shape types. Specifically, passing a positive `skin_factor` value would deflate a polygon, but inflate all the other shapes.
This commit makes the behavior consistent: `skin_factor > 0` implies in inflation for all shapes, including polygons.
Here's some sample code to test this change:
```c
c2Circle circ = {{0.0, 0.0}, 1.0};
c2Inflate(&circ, C2_TYPE_CIRCLE, 0.1);
printf("Inflated circle: p=(%f, %f) r=%f\n", circ.p.x, circ.p.y, circ.r);
c2Poly poly = {
3,
{{-1.0, -1.0}, {1.0, -1.0}, {0.0, 1.0}},
{},
};
c2MakePoly(&poly);
c2Inflate(&poly, C2_TYPE_POLY, 0.1);
printf("Inflated polygon: verts=[(%f, %f), (%f, %f), (%f, %f)]\n", poly.verts[0].x, poly.verts[0].y, poly.verts[1].x, …
```

Inflate polygons when passing `skin_factor > 0`

---

cute_tiled.h

The header `strings.h` is the C standard compliant header for `strncasecmp`, however some implementations also declare it in `string.h` (which is why it complies on some distributions but not others). An include for `strings.h` has been added. The `string,h` include has been preserved in the event that there are some non-compliant implementations. We don't want to accidentally break things for some users, and there are minimal downsides to doing this.

Added strings.h include to resolve strncasecmp on some systems

---

cute_sound.h

This pr fixes a few problems that caused the mixer to write loud pops at the end of sounds, and a crash that ocurred when the pitch of a sound was set to zero.

cutesound: fix popping issues & a mixer crash when pitch==0

---

cute_png.h

"nodes" is being freed and then immediately used. I dont think this is correct
compiler gives a warning for "use after free" without this change

[cute_png] moved free before usage

---

cute_tiled.h

Object-layers don't have tint, but they have another field for color. This reuses the tintcolor prop, that is used on tile-layers, since this serves the same purpose.
related: #407

cute_tiled: resolves #407 (object-layer color)

---

cute_tiled.h

This adds new adds imagewidth/imageheight. params for image-layers, and keeps it from crashing on maps saved in modern Tiled with image-layers.

cute_tiled: add layer imagewidth/imageheight

---

cute_tls.h

On the Windows implementation of cute_tls, if the response completely fills the 'ctx->incoming' buffer and there are still more bytes to be consumed then the subsequent call to `recv` will be passed a buffer with a capacity of 0, e.g.:
```c
while (...) {
int r = recv(ctx->sock, ctx->incoming + ctx->received, sizeof(ctx->incoming) - ctx->received, 0);
if (r == 0) {
// Server disconnected the socket.
ctx->state = TLS_STATE_DISCONNECTED;
break;
}
}
```
The expression of `sizeof(ctx->incoming) - ctx->received` will resolve to 0. `recv` will return 0 as there's no much space for the kernel to write to the buffer. This causes the loop to incorrectly identify that the server has disconnected the socket (rather that it ran out of space to offload more of the bytes from the response) and …

tls: Fix W32 TLS disconnect on large responses

---

cute_tiled.h

I would like to prefix this PR with a disclaimer that I am not a C/C++ developer; I am using cute_tiled.h in a Zig project and came across this issue.
I had a problem where my program would crash when loading a Tiled map with the background color set to any color that has an alpha of 255. The error was as follows:
```
thread 86737 panic: left shift of 255 by 24 places cannot be represented in type 'int'
/home/elnu/.cache/zig/p/N-V-__8AAEmvJgEZ0CqpksmguOCp2n4BK3cpgIttoaLpYC49/cute_tiled.h:1664:25: 0x1174865 in cute_tiled_read_hex_int_internal (/home/elnu/Projects/shino/src/cute_tiled.c)
uint32_t alpha = 0xFF << 24;
```
This is caused because the `0xFF` literal is being interpreted as a signed `int`, not a `uint32_t` despite the variable type. This PR explicitly makes the literal unsigned, …

cute_tiled: fix bit shifting to use unsigned literal for alpha, fixes loading of background colors with alpha of 255
