RandyGaul/cute_headers

- tinytime.h
Negative values of ttTime() is fixed.
> fix ttTime on linux

- tinyc2.h
I needed a generic raycast function along the line of c2Collide, so i made one :)
> tinyc2: Add generic raycast function

- .gitignore
- cute_path.h
- test_cute_path/Makefile
- test_cute_path/main.c
Fix test errors in cute_path.h
> Add test_cute_path

- cute_png.h
> Fix sizeof expression passed to memset for lookup array

- cute_png.h
- calculating `first_bytes` only works when the pointer mod 4 = 0 or 2, when the pointer mod 4 = 1 or 3 `s->words` won't result in a word aligned pointer. Since the passed pointer internally is always a malloc'ed pointer + 2, this bug doesn't manifest. Considering cp_inflate is not static, it should be correct on every input buffer however.
- the final bytes mechanism doesn't work: values get calculated wrong and consequently it just reads words past the `in` buffer. Again this doesn't manifest internally since after the deflate buffer there is a 4-byte checksum so it has some leeway to buffer overflow. 
- there's no would_overflow check before peeking bits in `cp_decode`. The check in `cp_read_bits` doesn't account for the `count` bits already present in the buffer.
> Fix memory bugs in cp_inflate

- cute_png.h
As mentioned in #139 
> Feel free to add yourself as a contributor in the docs, in the form of a pull-request! I’d like to get your name in there.
Glad these bugfixes are appreciated!
> Add contributor to cute_png

- cute_sound.h
> Comment fix

- cute_sound.h
* Added void* dsp_context member to cs_context_t
* Added void* dsp_mixer member to cs_playing_sound_def_t and cs_playing_sound_t
* Added getters and setters for the dsp_context
* Added cute_dsp callback code to cs_mix
> Added support for the cute_dsp library to cute_sound.

- cute_sound.h
Previously, the user created a dsp mixer themselves, and attached it to a play_sound_def, which would then be passed on to a playing_sound when play_sound was called. However play_sound_defs can be used for more than one playing_sound while mixers can only be used for one playing_sound.
So callbacks were added to cute_sound which allow play_sound_defs to store a ptr to mixer_defs which are passed into the callback to create a dsp mixer only when play_sound is called, attaching it to the playing_sound then. Another callback was added for when the playing sound is done playing that releases the mixer.
> Added callbacks to create mixers, cute_dsp

- cute_png.h
cute_png currently messes up on PNG's with a filter for the first scanline that accesses the previous scanline. It is specified that when unfiltering the first scanline, the previous line is supposed to be all zero. cute_png however treats the previous scanline as the current scanline, yielding incorrect results.
```C
uint8_t *prev = raw;
```
This PR fixes it by unrolling the first iteration out of the loop, which is a bit more code, but it avoids extra branching or allocation of an array of zeros.
> Fix wrong unfilter values for first scanline (cute_png)

- cute_c2.h
See issue #149
Note: I'm going to create a separate pull request for the breaking change mentioned there
> Added CUTE_C2_API define

- cute_c2.h
- examples_cute_gl_and_c2/main.cpp
> Changed C2_TYPE enum

- cute_sound.h
This patch probably doesn't affect #162
I've compiled with various combinations of C99, C++14, GCC, MinGW, ALSA, DirectSound, and SDL, doing my best to get rid of compile-time warnings and errors. I can't vouch for how well it all works, but at least it now builds without too many problems on the platforms that matter to me.
I replaced `usleep` with `nanosleep` for sub-second pauses since `usleep` is deprecated. I used [this](https://stackoverflow.com/questions/17118105/replacing-usleep-with-nanosleep) as a guide. It's still a total loss when compiling in C99 mode without `#define _DEFAULT_SOURCE` at the top of the translation unit, but I think it's a step in the right direction. Assumes that `cs_sleep` will always be called with values less than 1000.
Many of the C++-related errors came …
> cute_sound.h: Improve compatibility with Linux and C++

- cute_sound.h
Fixes #184
I will leave documentation and versioning decisions (if any) to Randy.
> cute_sound.h: Add CUTE_SOUND_SCALAR_MODE

- cute_tiled.h
Use __builtin_trap() to abort program when using Clang to avoid null-dereference warning.
> Clang: avoid null-dereference warning

- cute_tiled.h
> Fix uninitialised variable issue as reported by Valgrind

- cute_aseprite.h
The closing comment deliminator was wrong
> Cute Aseprite comment fixup

- cute_tiled.h
Fixed a endif-labels warning and cleaned whitespace.
> cute_tiled: fix warning and clean whitespace

- cute_aseprite.h
Was looking to either change, or disable the file loading, so this is what I came up with. I'm not sure if this is the appropriate way of handling it. If you have other suggestions, I'm all ears!
> aseprite: Allow changing File IO functions

- cute_png.h
This change follows up from https://github.com/RandyGaul/cute_headers/pull/246 and adds the File IO function definitions to cute_png.
> png: Allow changing File IO functions

- cute_math2d.h
(see https://github.com/RandyGaul/cute_headers/issues/253, credit @zshoals)
> Fix ray_to_halfpsace typo

- cute_spritebatch.h
I still need to do the same thing for texture sorting. But the problem it will expose the internal structure. I will need to do it tomorrow after discussion.
> optional sprites_sorter_callback to allow users to plug their own sprites sorting algorithm

- cute_spritebatch.h
Sorry, I missed setting sprites_scratches to 0.
> Forgot to reset the scratch space to 0

- cute_spritebatch.h
Add <stdbool.h> to make bool available when compiling as C
> Add <stdbool.h> to make bool available when compiling as C

- cute_path.h
> cute_path.h: fix path_pop_ex for relative paths

- cute_tiled.h
C89 provides that variables are declared at the beginning of their scope. In addition, variables cannot be declared in for-loops.
This problem mainly affects older compilers, such as GCC 2.9-psion-98r2 in my case.
> Adjust variable declarations to be able to compile it using a pre-C99 compiler

- cute_tiled.h
- Add a case for the new "class" field of objects (Tiled 1.9)
- Add better treatment for the "text" field, still unimplemented
> Improve behaviour for unimplemented fields

- cute_sound.h
correcting arguments to `cs_pull_bytes(...)` :)
Thanks!
> Small bug-fix cute_sound on apple

- cute_tiled.h
Support for "Repeat X" and "Repeat Y" image layer fields
> Added support for repeatx and repeaty fields

- cute_tiled.h
Added comments missing from the last commit.
> Added comments for image repeatx/repeaty fields

- cute_aseprite.h
Added support for ase_tag_t repeat field
> cute_aseprite: Added support for ase_tag_t repeat field

- cute_tiled.h
This fixes the git conflict that happened from https://github.com/RandyGaul/cute_headers/commit/613c97861b99cbb59530d39e4ac49a74594f7fbf
> tiled: Fix color conflicts

- cute_sound.h
Panning control for active sounds
> Sound panning

- cute_sound.h
https://github.com/RandyGaul/cute_framework/pull/162
crash fix when sample index < 0 and when looping with negative pitch to not have any audio clipping
> negative pitch crash fix

- README.md
> Fix STB link pointing to Google interstitial
